config-version: 2
name: 'sap'
version: '0.1.0'
require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  sap:
    +materialized: table
    +schema: sap

vars:
  sap:
    ## Staging Models
    mara: "{{ ref('stg_sap__mara') }}"
    ska1: "{{ ref('stg_sap__ska1') }}"