name: 'sap_integration_tests'
version: '0.1.0'
profile: 'integration_tests'
config-version: 2

models: 
  +materialized: table

vars:
  sap_schema: sap_integration_tests

  sap_source:
    sap_mara_identifier: ""